config/routes.rb
Rails.application.routes.draw do
  resources :repos

  resources :orgs

  resources :events

   root 'events#index'

end

app/models/actor.rb
class Actor
 include Mongoid::Document

	field :_id, type: Integer
	field :login, type: String
	field :gravatar_id, type: Integer
	field :url, type: String
	field :avatar_url, type: String

	embedded_in :event

end

app/models/author.rb
class Author
  include Mongoid::Document

  embeds_many :events

  field :email, type: String
  field :name, type: String
  
end

app/models/commit.rb
class Commit
  include Mongoid::Document
	has_one :author

  	field :sha, type: String
  	field :message, type: String
  	embedded_in :event
  
end

app/models/event.rb
class Event
  include Mongoid::Document
  has_one :org
  has_one :repo
  
  field :id, type: String
  field :type, type: String
  field :public, type: Mongoid::Boolean
end

app/models/org.rb
class Org
  include Mongoid::Document
  field :id, type: Integer
  field :login, type: String
  field :gravatar_id, type: String
  field :url, type: String
  field :avatar_url, type: String
end

app/models/payload.rb
class Payload
  include Mongoid::Document

	field :push_id, type: Integer
	field :size, type: Integer
	field :distinct_size, type: Integer


  	field :ref, type: String
  	field :head, type: String
  	field :before, type: String
  	field :commits, type: []

  	embedded_in :event
 
  
end

app/models/repo.rb
class Repo
  include Mongoid::Document
	belongs_to :Event

  field :id, type: Integer
  field :name, type: String
  field :url, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
require 'gchart'

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    @array_chart = [] 


    @numberPushEvent = Event.where(type: 'PushEvent').count
    @numberIssueCommentEvent = Event.where(type: 'IssueCommentEvent').count
    @numberIssuesEvent = Event.where(type: 'IssuesEvent').count
    @numberCreateEvent = Event.where(type: 'CreateEvent').count
    @numberWatchEvent = Event.where(type: 'WatchEvent').count
    @numberPullRequestEvent = Event.where(type: 'PullRequestEvent').count
    @numberDeleteEvent = Event.where(type: 'DeleteEvent').count

    @numberPrivateEvent = Event.where(public: 'false')
    @numberPublicEvent = Event.where(public: 'true')

    print 'number de ouf: '
    print @numberPublicEvent


    @chartGlobal = GChart.pie(:width =>500,
     :height => 500,
     :data => [@numberPushEvent, @numberIssuesEvent,
       @numberCreateEvent, @numberWatchEvent,@numberIssueCommentEvent,@numberPullRequestEvent,@numberDeleteEvent],
       :extras => { "chdl" => "PushEvent|IssueCommentEvent|IssuesEvent|CreateEvent|WatchEvent|PullRequestEvent|DeleteEvent"}
       ).to_url

    @array_chart.push(@chartGlobal)

    # @chartPrivate = GChart.bar(:width =>500,
    #  :height => 500,
    #  :data => [@numberPrivateEvent, @numberPublicEvent]).to_url  

    # @array_chart.push(@chartPrivate)


    @array_chart 




  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:id, :type, :public)
    end
  end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = Org.all
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/new
  def new
    @org = Org.new
  end

  # GET /orgs/1/edit
  def edit
  end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = Org.new(org_params)

    respond_to do |format|
      if @org.save
        format.html { redirect_to @org, notice: 'Org was successfully created.' }
        format.json { render :show, status: :created, location: @org }
      else
        format.html { render :new }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    respond_to do |format|
      if @org.update(org_params)
        format.html { redirect_to @org, notice: 'Org was successfully updated.' }
        format.json { render :show, status: :ok, location: @org }
      else
        format.html { render :edit }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    respond_to do |format|
      format.html { redirect_to orgs_url, notice: 'Org was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:id, :login, :gravatar_id, :url, :avatar_url)
    end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url, notice: 'Repo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:id, :name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<%= image_tag(@array_chart[0]) %>
<%= image_tag(@array_chart[1]) %>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Type</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.type %></td>
        <td><%= event.public %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>


<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @event.id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Public:</strong>
  <%= @event.public %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestMONGO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orgs/_form.html.erb
<%= form_for(@org) do |f| %>
  <% if @org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@org.errors.count, "error") %> prohibited this org from being saved:</h2>

      <ul>
      <% @org.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :gravatar_id %><br>
    <%= f.text_field :gravatar_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :avatar_url %><br>
    <%= f.text_field :avatar_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orgs/edit.html.erb
<h1>Editing Org</h1>

<%= render 'form' %>

<%= link_to 'Show', @org %> |
<%= link_to 'Back', orgs_path %>

app/views/orgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orgs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Login</th>
      <th>Gravatar</th>
      <th>Url</th>
      <th>Avatar url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orgs.each do |org| %>
      <tr>
        <td><%= org.id %></td>
        <td><%= org.login %></td>
        <td><%= org.gravatar_id %></td>
        <td><%= org.url %></td>
        <td><%= org.avatar_url %></td>
        <td><%= link_to 'Show', org %></td>
        <td><%= link_to 'Edit', edit_org_path(org) %></td>
        <td><%= link_to 'Destroy', org, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Org', new_org_path %>

app/views/orgs/new.html.erb
<h1>New Org</h1>

<%= render 'form' %>

<%= link_to 'Back', orgs_path %>

app/views/orgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @org.id %>
</p>

<p>
  <strong>Login:</strong>
  <%= @org.login %>
</p>

<p>
  <strong>Gravatar:</strong>
  <%= @org.gravatar_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @org.url %>
</p>

<p>
  <strong>Avatar url:</strong>
  <%= @org.avatar_url %>
</p>

<%= link_to 'Edit', edit_org_path(@org) %> |
<%= link_to 'Back', orgs_path %>

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing Repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repos</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.id %></td>
        <td><%= repo.name %></td>
        <td><%= repo.url %></td>
        <td><%= link_to 'Show', repo %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New Repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @repo.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repo.url %>
</p>

<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>